#include "led.h"

void LED_Configuration()
{
	RCC_AHB1PeriphClockCmd(RCC_AHB1Periph_GPIOA, ENABLE);
	GPIO_Set(GPIOA,PIN4|PIN5|PIN6|PIN7,GPIO_MODE_OUT,GPIO_OTYPE_PP,GPIO_SPEED_2M,GPIO_PUPD_NONE);
	LED_RED_OFF;LED_GREEN_OFF;LED_YELLOW_OFF;LED_BLUE_OFF;
}

void Led_Show(void)
{
	LED_RED_ON;Delay_ms(500);
	LED_RED_OFF;Delay_ms(500);
	LED_YELLOW_ON;Delay_ms(500);
	LED_YELLOW_OFF;Delay_ms(500);
	LED_BLUE_ON;Delay_ms(500);
	LED_BLUE_OFF;Delay_ms(500);
	LED_GREEN_ON;Delay_ms(500);
	LED_GREEN_OFF;Delay_ms(500);
}

